# -*- coding: utf-8 -*-
"""RetailAssist_LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LRwQC_RLDjodMwlxn_44H6bi4SZf1J1O

# RetailAssist-LLM: A Domain-Specific Customer Support Chatbot for E-commerce using TinyLlama and LoRA Fine-Tuning

Contribution : Vishal Kumar Singh (Individual)

Github link : https://github.com/CodesByVishal/IndustryGPT-Specialized-LLM-Bot-Using-Pre-Trained-Models-RetailAssist-LLM

## Abstract

This project develops a domain-specific customer support assistant for the retail and
e-commerce sector by fine-tuning a compact open-weight language model,
`TinyLlama-1.1B-Chat`, on the Bitext customer support corpus using Low-Rank Adaptation
(LoRA). The work covers the full applied machine-learning pipeline: exploratory data
analysis of the support corpus, a reproducible cleaning and splitting procedure,
parameter-efficient supervised fine-tuning under a constrained single-GPU budget, and a
structured evaluation combining text-overlap metrics with a support-action coverage
heuristic on a held-out test set. The resulting model is exposed through an interactive
interface for qualitative inspection. The study demonstrates that parameter-efficient
adaptation of a small base model yields a usable, domain-aware support assistant while
remaining executable on freely available hardware.

## Project overview

- **Industry:** Retail and E-commerce.
- **Goal:** Produce a customer-support chatbot that answers common e-commerce service
  queries (order tracking, returns, refunds, damaged items, account and payment issues)
  in a concise, support-oriented manner.
- **Problem statement:** General-purpose chatbots lack the domain grounding and
  consistent, policy-aware phrasing expected of e-commerce support. This project adapts a
  small base model to the customer-support domain and evaluates whether the adaptation
  produces measurable domain awareness.
- **Approach:** A domain support dataset (Bitext) is analysed and cleaned, split into
  train/validation/test partitions, and used to fine-tune TinyLlama with LoRA. The model
  is evaluated on a held-out test set and served through an interactive interface.

## 1. Problem Statement and Industry Context

Customer support is one of the highest-volume natural-language workloads in retail and
e-commerce. A large fraction of incoming contacts are repetitive, intent-driven requests
such as order status, returns, refunds, and account access. General-purpose conversational
models handle open-domain language well but are not aligned to the phrasing, tone, and
procedural expectations of a specific support operation, and they readily fabricate
order-specific details that a support assistant must never invent.

A domain-specific support assistant matters for several reasons:

- **Consistency.** Responses should follow predictable, policy-consistent patterns rather
  than varying arbitrarily between phrasings.
- **Intent coverage.** Retail support concentrates on a bounded set of query classes,
  which a domain-adapted model can learn to serve reliably.
- **Safety of claims.** The assistant must request identifiers (order or account numbers)
  rather than hallucinate them.

The dominant query classes in retail support, which frame the scope of this project, are:

1. Order tracking and delivery status.
2. Returns and exchanges.
3. Refunds and billing.
4. Damaged, defective, or incorrect items.
5. Account and login issues.

For these classes, response relevance, policy consistency, and awareness of missing
context (for example, an absent order number) are the primary quality criteria, and they
motivate both the fine-tuning objective and the evaluation design used below.

## 2. Industry Selection and Dataset Justification

**Selected industry.** Retail and e-commerce. Customer support in this sector is a
well-defined, high-volume NLP application with clear intent structure, making it a
suitable target for domain adaptation of a language model.

**Dataset.** The Bitext *Customer Support LLM Chatbot Training Dataset* is a publicly
available, instruction-response corpus designed specifically for training support
assistants. Each record pairs a customer instruction with a support-style response and is
annotated with a coarse `category` and a finer `intent` label.

**Relevance to the industry.** The dataset's intents map directly onto the retail support
query classes above: order handling, cancellation, delivery/shipping, refunds, invoicing
and payment, and account management. This alignment makes it appropriate for adapting a
model to e-commerce support tasks rather than generic dialogue.

**Known limitations of the dataset**, which are revisited in the limitations section:

- Responses are **templated**, containing placeholders such as `{{Order Number}}`; the
  language is therefore more uniform than real production support logs.
- The corpus is predominantly **single-turn**, so it does not capture the full multi-turn
  complexity of real conversations.
- It encodes **generic** support behaviour rather than any specific company's policies.

These limitations are acceptable for a capstone whose objective is to demonstrate
domain adaptation methodology, and they are accounted for in the evaluation and discussion.

## 3. Environment Setup

The notebook targets a Google Colab runtime with a single T4 GPU. The Colab image ships an
older `torchao` build that is incompatible with the PEFT version used here; it is removed
after installation to avoid an import error.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q transformers peft datasets accelerate pandas matplotlib seaborn scikit-learn rouge-score gradio
# %pip uninstall -q -y torchao

from google.colab import drive
drive.mount('/content/drive')

"""## 4. Persistence and Reuse Configuration

Fine-tuning is the expensive step in this pipeline. To support reproducibility and fast
iteration during report and presentation preparation, cleaned data splits and trained
model artifacts are persisted to Google Drive. Subsequent runs detect existing artifacts
and reuse them, so the notebook does not retrain unless explicitly instructed.

The project directory is organised into subfolders for data, splits, model artifacts,
training checkpoints, metrics, and figures. The boolean flags below control whether cached
outputs are loaded or regenerated.
"""

from pathlib import Path

PROJECT_DIR     = Path("/content/drive/MyDrive/RetailAssist_LLM")
DATA_DIR        = PROJECT_DIR / "data"
SPLITS_DIR      = PROJECT_DIR / "splits"
ARTIFACTS_DIR   = PROJECT_DIR / "artifacts"
CHECKPOINTS_DIR = PROJECT_DIR / "checkpoints"
METRICS_DIR     = PROJECT_DIR / "metrics"
FIGURES_DIR     = PROJECT_DIR / "figures"

for directory in [DATA_DIR, SPLITS_DIR, ARTIFACTS_DIR, CHECKPOINTS_DIR, METRICS_DIR, FIGURES_DIR]:
    directory.mkdir(parents=True, exist_ok=True)

# Reuse behaviour. Set the FORCE_ flags to True to regenerate artifacts from scratch.
LOAD_SPLITS_FROM_DRIVE          = True
SAVE_SPLITS_TO_DRIVE            = True
LOAD_TRAINED_ADAPTER_FROM_DRIVE = True
SAVE_TRAINED_ADAPTER_TO_DRIVE   = True
FORCE_REPROCESS_DATA            = False
FORCE_RETRAIN_MODEL             = False

print("Project directory:", PROJECT_DIR)

"""### 4.1 Reproducibility controls

A single random seed is applied across Python, NumPy, and PyTorch, and passed to the
training arguments, so that data splitting and training are reproducible across runs.
"""

import random
import numpy as np
import torch
from transformers import set_seed

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
set_seed(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEVICE)
assert DEVICE == "cuda", "A GPU runtime is required. Enable a T4 GPU under Runtime settings."

"""### 4.2 Model and training configuration

All model, data, and training hyperparameters are declared in a single cell. The prompt
template is shared between training and inference to keep the two consistent.
"""

import os

os.environ["HF_TOKEN"] = "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"

BASE_MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
DATASET_ID = "bitext/Bitext-customer-support-llm-chatbot-training-dataset"

# Supervised fine-tuning template. Identical formatting is used at inference time.
PROMPT_TEMPLATE = "### Instruction:\n{instruction}\n\n### Response:\n{response}"

# Cleaning thresholds
MIN_INSTRUCTION_WORDS = 3
MIN_RESPONSE_WORDS    = 8

# Training hyperparameters
MAX_LEN      = 256
EPOCHS       = 3
BATCH_SIZE   = 16
LR           = 2e-4
WEIGHT_DECAY = 0.01
WARMUP_RATIO = 0.03

# LoRA configuration
LORA_R       = 16
LORA_ALPHA   = 32
LORA_DROPOUT = 0.05
LORA_TARGETS = ["q_proj", "v_proj"]

# Evaluation
EVAL_SAMPLE_SIZE = 120

ADAPTER_PATH = ARTIFACTS_DIR / "lora_adapter"
TRAINING_LOG_PATH = METRICS_DIR / "training_log.json"

"""## 5. Exploratory Data Analysis

The dataset is inspected prior to any preprocessing so that cleaning decisions are
motivated by observed properties rather than assumptions. The raw corpus is loaded in full
for analysis.
"""

from datasets import load_dataset
import pandas as pd

raw = load_dataset(DATASET_ID, split="train")
df_raw = raw.to_pandas()[["instruction", "response", "category", "intent"]]

print("Rows:", len(df_raw))
df_raw.head()

"""### 5.1 Dataset overview

Basic structure, label cardinality, missing values, and duplicate counts.
"""

print("Shape:", df_raw.shape)
print("Columns:", list(df_raw.columns))
print("Unique categories:", df_raw["category"].nunique())
print("Unique intents:", df_raw["intent"].nunique())

print("\nMissing values per column:")
print(df_raw.isnull().sum())

print("\nExact duplicate rows:", int(df_raw.duplicated().sum()))
print("Duplicate instructions:", int(df_raw["instruction"].duplicated().sum()))

"""The corpus contains a moderate number of records spanning a small, fixed label space of
categories and intents. There are no missing values in the instruction or response fields.
A share of instructions repeat verbatim, which motivates deduplication during cleaning.

### 5.2 Intent distribution

The frequency of each intent indicates how evenly the support tasks are represented.
"""

import matplotlib.pyplot as plt

intent_counts = df_raw["intent"].value_counts()

fig, ax = plt.subplots(figsize=(8, 7))
intent_counts.sort_values().plot(kind="barh", ax=ax, color="steelblue")
ax.set_title("Intent distribution in the Bitext customer support corpus")
ax.set_xlabel("Number of examples")
ax.set_ylabel("Intent")
plt.tight_layout()
plt.savefig(FIGURES_DIR / "intent_distribution.png", dpi=150)
plt.show()

intent_counts

"""The intents are relatively balanced, with comparable counts per class. This reduces the
risk that the fine-tuned model is dominated by a small number of intents and supports a
stratified split on the intent label.

### 5.3 Text length distributions

Instruction and response lengths (in words) determine an appropriate maximum sequence
length for tokenization and reveal outliers.
"""

df_raw["instruction_words"] = df_raw["instruction"].str.split().str.len()
df_raw["response_words"] = df_raw["response"].str.split().str.len()

print("Descriptive statistics (words):")
print(df_raw[["instruction_words", "response_words"]].describe())

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].hist(df_raw["instruction_words"], bins=40, color="steelblue")
axes[0].set_title("Customer instruction length")
axes[0].set_xlabel("Words")
axes[0].set_ylabel("Frequency")
axes[1].hist(df_raw["response_words"], bins=40, color="indianred")
axes[1].set_title("Support response length")
axes[1].set_xlabel("Words")
axes[1].set_ylabel("Frequency")
plt.tight_layout()
plt.savefig(FIGURES_DIR / "length_distributions.png", dpi=150)
plt.show()

"""Instructions are short, while responses are longer and more variable. The bulk of
responses fall well within a few hundred tokens, which justifies a maximum sequence length
of 256 tokens: it accommodates the large majority of examples while limiting memory use on
a T4 GPU.

### 5.4 Length spread and outliers

A boxplot summarises the spread and highlights long-tail outliers in both fields.
"""

fig, ax = plt.subplots(figsize=(7, 4))
ax.boxplot([df_raw["instruction_words"], df_raw["response_words"]],
           labels=["Instruction", "Response"], showfliers=True)
ax.set_title("Text length spread")
ax.set_ylabel("Words")
plt.tight_layout()
plt.savefig(FIGURES_DIR / "length_boxplot.png", dpi=150)
plt.show()

"""Responses show a wider interquartile range and a longer upper tail than instructions.
The outliers are legitimate long responses rather than corruption, so they are retained
and handled through truncation at the configured maximum length.

### 5.5 Data quality inspection

The templated nature of the corpus is quantified by counting placeholder patterns of the
form `{{...}}`, together with short samples and duplicate instructions.
"""

import re

placeholder_re = re.compile(r"\{\{.*?\}\}")

quality = pd.DataFrame({
    "check": [
        "responses containing placeholders",
        "instructions containing placeholders",
        "instructions below minimum length",
        "responses below minimum length",
        "duplicate instructions",
        "total null values",
    ],
    "count": [
        int(df_raw["response"].str.contains(placeholder_re).sum()),
        int(df_raw["instruction"].str.contains(placeholder_re).sum()),
        int((df_raw["instruction_words"] < MIN_INSTRUCTION_WORDS).sum()),
        int((df_raw["response_words"] < MIN_RESPONSE_WORDS).sum()),
        int(df_raw["instruction"].duplicated().sum()),
        int(df_raw.isnull().sum().sum()),
    ],
})
quality

"""### 5.6 EDA conclusions

- The corpus is clean and well structured, with balanced intents and no missing values.
- Responses are systematically templated with `{{...}}` placeholders, confirming the need
  to normalise these tokens before training.
- A subset of instructions are exact duplicates and are removed to avoid over-representing
  particular phrasings.
- Length statistics support a 256-token maximum sequence length.

These observations directly determine the preprocessing steps applied next.

## 6. Data Cleaning and Preprocessing

Preprocessing normalises placeholder markup, collapses whitespace, removes null and
overly short records, and deduplicates on the instruction field. Each filter's effect on
the row count is recorded so that the impact of cleaning is transparent.

Placeholder braces are stripped while retaining the enclosed field name as readable text
(for example, `{{Order Number}}` becomes `Order Number`), which preserves the semantic
content of the response without exposing template syntax to the model.
"""

def normalize_text(text):
    text = re.sub(r"\{\{|\}\}", "", text)   # drop placeholder braces, keep the field name
    text = re.sub(r"\s+", " ", text)        # collapse whitespace
    return text.strip()

work = df_raw.copy()
n_raw = len(work)

work["instruction"] = work["instruction"].map(normalize_text)
work["response"] = work["response"].map(normalize_text)

work = work.dropna(subset=["instruction", "response"])
n_after_null = len(work)

work["instruction_words"] = work["instruction"].str.split().str.len()
work["response_words"] = work["response"].str.split().str.len()

before_short = len(work)
work = work[(work["instruction_words"] >= MIN_INSTRUCTION_WORDS)
            & (work["response_words"] >= MIN_RESPONSE_WORDS)]
removed_short = before_short - len(work)

before_dup = len(work)
work = work.drop_duplicates(subset="instruction")
removed_dup = before_dup - len(work)

clean_df = work[["instruction", "response", "category", "intent"]].reset_index(drop=True)
n_clean = len(clean_df)

print(f"Cleaned dataset: {n_clean} rows")
clean_df.head()

"""### 6.1 Cleaning impact report

The table quantifies how many records were removed at each stage.
"""

cleaning_report = pd.DataFrame(
    [
        ("Raw rows", n_raw),
        ("Removed: null instruction/response", n_raw - n_after_null),
        ("Removed: below minimum length", removed_short),
        ("Removed: duplicate instructions", removed_dup),
        ("Final cleaned rows", n_clean),
    ],
    columns=["stage", "rows"],
)
cleaning_report.to_csv(METRICS_DIR / "cleaning_report.csv", index=False)
cleaning_report

"""## 7. Train / Validation / Test Split

The cleaned corpus is partitioned into training (80%), validation (10%), and test (10%)
sets using a fixed seed. The split is **stratified by intent** so that every partition
preserves the intent distribution observed during EDA. The validation set is used for
loss monitoring during training; the test set is held out entirely and used only for the
final evaluation, providing an unbiased estimate of domain performance.

If split files already exist in Drive and reprocessing is not forced, they are loaded
directly; otherwise they are created from the cleaned data and saved.
"""

from sklearn.model_selection import train_test_split

def _load_cached_splits():
    return (
        pd.read_csv(SPLITS_DIR / "train.csv"),
        pd.read_csv(SPLITS_DIR / "val.csv"),
        pd.read_csv(SPLITS_DIR / "test.csv"),
    )

splits_exist = all((SPLITS_DIR / f"{name}.csv").exists() for name in ["train", "val", "test"])

if LOAD_SPLITS_FROM_DRIVE and splits_exist and not FORCE_REPROCESS_DATA:
    train_df, val_df, test_df = _load_cached_splits()
    print("Loaded cached train/validation/test splits from Google Drive.")
else:
    train_val_df, test_df = train_test_split(
        clean_df, test_size=0.10, random_state=SEED, stratify=clean_df["intent"])
    train_df, val_df = train_test_split(
        train_val_df, test_size=1 / 9, random_state=SEED, stratify=train_val_df["intent"])

    train_df = train_df.reset_index(drop=True)
    val_df = val_df.reset_index(drop=True)
    test_df = test_df.reset_index(drop=True)

    if SAVE_SPLITS_TO_DRIVE:
        train_df.to_csv(SPLITS_DIR / "train.csv", index=False)
        val_df.to_csv(SPLITS_DIR / "val.csv", index=False)
        test_df.to_csv(SPLITS_DIR / "test.csv", index=False)
        print("Created splits from cleaned data and saved them to Google Drive.")
    else:
        print("Created splits from cleaned data (not persisted).")

print(f"Train: {len(train_df)}   Validation: {len(val_df)}   Test: {len(test_df)}")

"""## 8. Model Selection Rationale

`TinyLlama-1.1B-Chat` is selected as the base model. The choice reflects the compute
constraints of a single-GPU capstone environment and the nature of the task:

- **Model size versus feasibility.** At 1.1B parameters, the model fits in the memory of a
  T4 GPU together with a training batch and trains within a single Colab session. Larger
  instruction-tuned models would exceed the available budget or require quantised training
  that complicates reproducibility.
- **Parameter-efficient fine-tuning.** LoRA adapts the model by training a small number of
  low-rank matrices injected into the attention projections while the base weights remain
  frozen. This reduces the number of trainable parameters by more than two orders of
  magnitude, lowers memory pressure, and yields adapter files of a few megabytes that are
  convenient to persist and reload.
- **Why not full fine-tuning.** Updating all 1.1B parameters is unnecessary for adapting to
  a bounded support domain and is not practical on a T4. LoRA achieves domain adaptation at
  a fraction of the cost with negligible storage overhead.

This configuration is a defensible engineering choice for demonstrating domain adaptation
under realistic academic resource limits.

## 9. Fine-Tuning Methodology

Training follows a supervised fine-tuning setup. Each example is rendered with the shared
prompt template and tokenized with dynamic padding at the batch level. Labels are the input
token identifiers with padding positions masked, as produced by the language-modelling data
collator.

The tokenizer's end-of-sequence token is used for padding. Sequences are truncated at 256
tokens, consistent with the length analysis in the EDA section.
"""

from datasets import Dataset
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
tokenizer.pad_token = tokenizer.eos_token

def format_example(row):
    return PROMPT_TEMPLATE.format(instruction=row["instruction"], response=row["response"])

def build_tokenized_dataset(frame):
    texts = [format_example(row) for _, row in frame.iterrows()]
    dataset = Dataset.from_dict({"text": texts})
    return dataset.map(
        lambda batch: tokenizer(batch["text"], truncation=True, max_length=MAX_LEN),
        batched=True,
        remove_columns=["text"],
    )

train_dataset = build_tokenized_dataset(train_df)
val_dataset = build_tokenized_dataset(val_df)
print(f"Tokenized {len(train_dataset)} training and {len(val_dataset)} validation examples.")

"""The base model is loaded in half precision. If a trained adapter is present in Drive and
retraining is not forced, the adapter is loaded directly and training is skipped.
Otherwise a fresh LoRA adapter is attached; the trainable low-rank parameters are held in
full precision, which is required for stable mixed-precision optimisation.
"""

from transformers import AutoModelForCausalLM
from peft import LoraConfig, get_peft_model, PeftModel

adapter_exists = (ADAPTER_PATH / "adapter_config.json").exists()
use_cached_adapter = LOAD_TRAINED_ADAPTER_FROM_DRIVE and adapter_exists and not FORCE_RETRAIN_MODEL

base_model = AutoModelForCausalLM.from_pretrained(BASE_MODEL, dtype=torch.float16).to(DEVICE)

if use_cached_adapter:
    model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
    print("Loaded trained LoRA adapter from Drive. Training will be skipped.")
else:
    lora_config = LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        target_modules=LORA_TARGETS,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(base_model, lora_config)
    for parameter in model.parameters():
        if parameter.requires_grad:
            parameter.data = parameter.data.float()   # fp32 master weights for the adapter
    model.print_trainable_parameters()
    print("Initialized a fresh LoRA adapter. Training will run.")

"""### 9.1 Training hyperparameters

The hyperparameters are chosen for stable adaptation within one T4 session:

- **Epochs = 3.** Sufficient passes for the model to internalise the response style of the
  corpus without over-repeating a fixed set of examples.
- **Batch size = 16** with **maximum length 256**, which fits T4 memory in half precision.
- **Learning rate = 2e-4** with a **cosine schedule** and a short **warmup (3%)**, a
  standard configuration for LoRA adaptation.
- **Weight decay = 0.01** for mild regularisation.
- Validation loss is evaluated each epoch, and the training seed is fixed for
  reproducibility.

Training runs only when no cached adapter is available. When training occurs, the final
adapter, the tokenizer, and the full training log are written to Drive.
"""

import json
from transformers import DataCollatorForLanguageModeling, Trainer, TrainingArguments

if not use_cached_adapter:
    collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

    training_args = TrainingArguments(
        output_dir=str(CHECKPOINTS_DIR),
        num_train_epochs=EPOCHS,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        learning_rate=LR,
        weight_decay=WEIGHT_DECAY,
        warmup_ratio=WARMUP_RATIO,
        lr_scheduler_type="cosine",
        fp16=True,
        eval_strategy="epoch",
        logging_steps=50,
        save_strategy="epoch",
        save_total_limit=1,
        seed=SEED,
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        data_collator=collator,
    )

    trainer.train()
    log_history = trainer.state.log_history

    if SAVE_TRAINED_ADAPTER_TO_DRIVE:
        model.save_pretrained(ADAPTER_PATH)
        tokenizer.save_pretrained(ADAPTER_PATH)
        with open(TRAINING_LOG_PATH, "w") as handle:
            json.dump(log_history, handle)
        print("Saved trained adapter, tokenizer, and training log to Drive.")
else:
    if TRAINING_LOG_PATH.exists():
        with open(TRAINING_LOG_PATH) as handle:
            log_history = json.load(handle)
        print("Loaded cached training log from Drive.")
    else:
        log_history = []
        print("No cached training log found; loss curves are unavailable for this run.")

"""## 10. Training Monitoring and Result Analysis

Training and validation loss are extracted from the training log and plotted against
optimisation steps. The training log is persisted, so the curves are available even when
the model is reloaded from cache rather than retrained.
"""

train_points = [(entry["step"], entry["loss"]) for entry in log_history if "loss" in entry]
eval_points = [(entry["step"], entry["eval_loss"]) for entry in log_history if "eval_loss" in entry]

if train_points:
    steps, losses = zip(*train_points)
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(steps, losses, label="Training loss", color="steelblue")
    if eval_points:
        eval_steps, eval_losses = zip(*eval_points)
        ax.plot(eval_steps, eval_losses, label="Validation loss", color="indianred", marker="o")
    ax.set_xlabel("Training step")
    ax.set_ylabel("Loss")
    ax.set_title("Training and validation loss")
    ax.legend()
    ax.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "loss_curves.png", dpi=150)
    plt.show()
else:
    print("No training-loss history is available to plot for this run.")

"""**Interpretation.** A monotonically decreasing training loss that stabilises indicates the
adapter is learning the response distribution of the corpus. Validation loss tracking the
training loss without diverging upward indicates the model is not overfitting within the
chosen number of epochs. Loss alone is a limited proxy for the quality of a generative
support assistant: it measures token-level likelihood, not whether responses are relevant,
policy-consistent, or free of fabricated details. The structured evaluation below addresses
these dimensions directly.

## 11. Bot Design and Inference Logic

At inference time a user query is inserted into the same instruction-response template used
for training, prefixed with a system specification that defines the assistant's behavioural
constraints for the retail support domain. The constraints target the quality criteria
identified in the problem statement: relevance, conciseness, a support-oriented tone,
avoidance of fabricated order details, and explicit requests for missing identifiers.

Generation uses sampling with a moderate temperature and nucleus filtering, together with a
repetition penalty and an n-gram block to suppress degenerate loops. Only the tokens
generated after the prompt are returned, and any text the model produces beyond the first
response turn is discarded.
"""

SYSTEM_PROMPT = """You are RetailAssist, a customer support assistant for an online retail and e-commerce store.

Response constraints:
- Answer directly and stop once the answer is complete; do not pad the reply.
- Keep answers concise and professional, typically two to three sentences.
- Do not add generic closing remarks, repeated offers of further help, or phrases such as "do not hesitate to reach out" or "we value your satisfaction".
- Do not fabricate order numbers, tracking numbers, dates, prices, or store policies.
- When an order or account identifier is required to proceed, request it explicitly.
- Restrict responses to retail and e-commerce customer support topics.
- For queries outside the defined support scope, respond helpfully without inventing domain details."""

model.eval()

def generate_response(message, max_new_tokens=160):
    prompt = f"{SYSTEM_PROMPT}\n\n" + PROMPT_TEMPLATE.format(instruction=message, response="")
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.6,
            top_p=0.9,
            do_sample=True,
            repetition_penalty=1.2,
            no_repeat_ngram_size=3,
            pad_token_id=tokenizer.eos_token_id,
        )
    generated = tokenizer.decode(output[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
    return generated.split("### Instruction:")[0].strip()

"""## 12. Structured Evaluation of Bot Performance

The model is evaluated on the held-out test set along three complementary dimensions:

1. **Qualitative inspection** of representative queries drawn from different support
   categories, each shown with its reference response and the model's output.
2. **Quantitative text-overlap metrics** (ROUGE) computed against reference responses on a
   sampled subset of the test set.
3. **A support-action coverage heuristic** that checks whether the model's response
   mentions domain keywords appropriate to the query's category, used to bucket responses
   into interpretable quality categories.

Generation is comparatively slow on a T4, so the quantitative metrics are computed on a
fixed random sample of the test set rather than the entire partition. The sample size is
declared in the configuration.

### 12.1 Qualitative evaluation on held-out examples

One representative example is drawn from each of the most frequent test categories. Because
these are held-out records, each has a reference response for comparison.
"""

pd.set_option("display.max_colwidth", 220)

selected_categories = test_df["category"].value_counts().index[:6]
qualitative_rows = []
for category in selected_categories:
    example = test_df[test_df["category"] == category].iloc[0]
    qualitative_rows.append({
        "category": category,
        "query": example["instruction"],
        "reference": example["response"][:180],
        "model_response": generate_response(example["instruction"])[:220],
    })

qualitative_df = pd.DataFrame(qualitative_rows)
qualitative_df

"""### 12.2 Quantitative metrics and support-action coverage

ROUGE-1, ROUGE-2, and ROUGE-L F-measures are averaged over the test sample. In parallel, a
keyword heuristic checks whether each response contains at least one action term relevant
to the true category, and a combined rule assigns each response to a qualitative bucket.
"""

from rouge_score import rouge_scorer

eval_df = test_df.sample(n=min(EVAL_SAMPLE_SIZE, len(test_df)), random_state=SEED).reset_index(drop=True)
scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

predictions = [generate_response(query) for query in eval_df["instruction"]]
eval_df["prediction"] = predictions

rouge_totals = {"rouge1": 0.0, "rouge2": 0.0, "rougeL": 0.0}
for reference, prediction in zip(eval_df["response"], predictions):
    scores = scorer.score(reference, prediction)
    for key in rouge_totals:
        rouge_totals[key] += scores[key].fmeasure

n_eval = len(eval_df)
rouge_scores = {
    "ROUGE-1": rouge_totals["rouge1"] / n_eval,
    "ROUGE-2": rouge_totals["rouge2"] / n_eval,
    "ROUGE-L": rouge_totals["rougeL"] / n_eval,
}
print("Averaged ROUGE on held-out sample:")
for name, value in rouge_scores.items():
    print(f"  {name}: {value:.3f}")

# Category-specific support-action keywords used for the coverage heuristic.
CATEGORY_KEYWORDS = {
    "ORDER":            ["order", "purchase", "item", "buy"],
    "DELIVERY":         ["deliver", "shipping", "ship", "track", "arrive"],
    "SHIPPING":         ["deliver", "shipping", "ship", "track", "arrive"],
    "REFUND":           ["refund", "money back", "reimburse", "return"],
    "CANCEL":           ["cancel"],
    "ACCOUNT":          ["account", "password", "login", "log in", "sign in", "email"],
    "PAYMENT":          ["payment", "pay", "card", "charge", "transaction"],
    "INVOICE":          ["invoice", "bill", "receipt"],
    "SHIPPING_ADDRESS": ["address", "shipping"],
    "SUBSCRIPTION":     ["subscription", "subscribe", "plan"],
    "NEWSLETTER":       ["newsletter", "subscribe", "email"],
    "CONTACT":          ["contact", "support", "agent", "representative", "help"],
    "FEEDBACK":         ["feedback", "complaint", "review", "sorry"],
}

def keyword_covered(response, category):
    text = response.lower()
    return any(keyword in text for keyword in CATEGORY_KEYWORDS.get(category, []))

def qualitative_bucket(response, reference, category):
    if len(response.split()) < 4:
        return "Incorrect / Incomplete"
    covered = keyword_covered(response, category)
    rouge_l = scorer.score(reference, response)["rougeL"].fmeasure
    if covered and rouge_l >= 0.30:
        return "Relevant / Correct"
    if covered or rouge_l >= 0.20:
        return "Partially Correct"
    return "Generic but Acceptable"

eval_df["keyword_covered"] = [keyword_covered(p, c) for p, c in zip(predictions, eval_df["category"])]
eval_df["bucket"] = [qualitative_bucket(p, r, c)
                     for p, r, c in zip(predictions, eval_df["response"], eval_df["category"])]

coverage_rate = float(eval_df["keyword_covered"].mean())
print(f"Support-action keyword coverage: {coverage_rate:.3f}")
print("\nQualitative bucket counts:")
print(eval_df["bucket"].value_counts())

"""### 12.3 Evaluation visualisations

The averaged text-overlap metrics and the distribution of qualitative buckets are shown
side by side.
"""

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].bar(list(rouge_scores.keys()), list(rouge_scores.values()), color="steelblue")
axes[0].set_ylim(0, 1)
axes[0].set_ylabel("F-measure")
axes[0].set_title("Text-overlap metrics on held-out sample")

bucket_order = ["Relevant / Correct", "Partially Correct",
                "Generic but Acceptable", "Incorrect / Incomplete"]
bucket_counts = eval_df["bucket"].value_counts().reindex(bucket_order).fillna(0)
axes[1].bar(range(len(bucket_order)), bucket_counts.values, color="indianred")
axes[1].set_xticks(range(len(bucket_order)))
axes[1].set_xticklabels(bucket_order, rotation=20, ha="right")
axes[1].set_ylabel("Count")
axes[1].set_title("Qualitative evaluation categories")

plt.tight_layout()
plt.savefig(FIGURES_DIR / "evaluation_summary.png", dpi=150)
plt.show()

# Persist evaluation artifacts for the report and presentation.
eval_df[["category", "instruction", "response", "prediction", "keyword_covered", "bucket"]].to_csv(
    METRICS_DIR / "evaluation_results.csv", index=False)
qualitative_df.to_csv(METRICS_DIR / "qualitative_examples.csv", index=False)

evaluation_summary = {
    "rouge": rouge_scores,
    "keyword_coverage": coverage_rate,
    "bucket_counts": eval_df["bucket"].value_counts().to_dict(),
    "n_eval": n_eval,
}
with open(METRICS_DIR / "evaluation_summary.json", "w") as handle:
    json.dump(evaluation_summary, handle, indent=2)

print("Saved evaluation artifacts to Drive.")

"""### 12.4 Evaluation summary

The evaluation combines lexical overlap with a domain-coverage heuristic to characterise
performance beyond anecdotal inspection.

- **Domain awareness.** The support-action coverage rate indicates how often responses
  reference terminology appropriate to the query category, which is evidence that the
  fine-tuning induced domain adaptation rather than generic dialogue.
- **Overlap with references.** ROUGE scores are moderate, as expected for a generative model
  evaluated against a single templated reference: acceptable paraphrases are penalised by
  n-gram overlap, so these scores should be read as a lower bound on response quality.
- **Failure modes.** Residual weaknesses include occasional generic responses that satisfy
  tone but omit specific next steps, and the model's inability to reference real order data,
  which is a property of the offline setting rather than a training defect.

Together the metrics indicate that the adapted model is domain-aware and support-oriented,
with the main limitations attributable to the templated corpus and the absence of live
backend data.

## 13. Practical Relevance to Retail and E-commerce

A model of this kind is applicable as a first-line support layer in an e-commerce operation:

- **First-line response and FAQ deflection** for high-volume, low-complexity queries.
- **Returns and refunds guidance**, explaining the process and requesting the required
  identifiers.
- **Order issue triage**, classifying and drafting initial responses before human handoff.
- **Account and access assistance**, routing users through standard recovery steps.

In a production setting the model would sit behind a retrieval layer connected to policy
documents and an order-management system, so that responses are grounded in real data. The
present work establishes the domain-adaptation component of such a system.

## 14. Limitations and Failure Cases

- **Templated training data.** The Bitext corpus is synthetic and templated, so the model
  reproduces a more uniform style than real production support logs would require.
- **No personalisation or backend access.** The model has no connection to an order
  database and cannot provide real order-specific information.
- **Residual hallucination risk.** As a generative model it can still produce unsupported
  statements, mitigated but not eliminated by the system constraints.
- **Company-specific policies.** The model encodes generic support behaviour and would need
  further adaptation or retrieval grounding for a specific retailer's policies.
- **Limited conversational state.** The corpus is largely single-turn, so multi-turn
  context handling is weak.
- **Offline evaluation.** Evaluation is restricted to available held-out data and automatic
  proxies; it does not include live human judgement or A/B testing.
- **Base model capacity.** At 1.1B parameters the model has limited reasoning capacity
  compared with larger instruction-tuned models.

## 15. Future Improvements

- **Retrieval-augmented generation** over a policy and FAQ knowledge base to ground
  responses in authoritative content.
- **Order-management integration** so the assistant can act on real order and account data.
- **Stronger evaluation protocol**, including human annotation and inter-annotator
  agreement, and additional metrics such as BERTScore.
- **Multi-turn support data** to improve conversational state handling.
- **Guardrails and escalation logic** for safe handoff to human agents on sensitive or
  low-confidence queries.
- **Larger or more capable base models** where compute permits, to improve reasoning and
  instruction following.

## 16. Live Demonstration Interface

The trained assistant is exposed through an interactive interface for qualitative
inspection. The interface calls the same inference function used in evaluation, so the
demonstrated behaviour is consistent with the reported results. Example queries cover the
retail support categories analysed above.
"""

import gradio as gr

EXAMPLE_QUERIES = [
    "Where is my order? It has been four days since I placed it.",
    "How do I return a damaged item?",
    "I was charged twice for the same order. Can you help?",
    "I cannot log into my account. What should I do?",
    "I want to cancel an order I placed an hour ago.",
]

def chat_interface(message, history):
    return generate_response(message)

demo = gr.ChatInterface(
    fn=chat_interface,
    title="RetailAssist-LLM: Customer Support Assistant",
    description="Domain-specific support assistant for retail and e-commerce, fine-tuned from TinyLlama-1.1B with LoRA.",
    examples=EXAMPLE_QUERIES,
)

demo.launch(share=True)

"""## 17. Conclusion

This project adapted a compact open-weight language model to the retail and e-commerce
customer-support domain. Working from the Bitext support corpus, the study performed
exploratory analysis to characterise the data, applied a documented cleaning and
stratified splitting procedure, and fine-tuned TinyLlama-1.1B with LoRA under a single-GPU
budget. The model was assessed on a held-out test set using text-overlap metrics and a
support-action coverage heuristic, supported by training and evaluation visualisations, and
was made available through an interactive interface.

The results indicate that parameter-efficient fine-tuning of a small base model produces a
domain-aware support assistant whose responses are relevant and support-oriented, within
the limits imposed by a templated corpus and the absence of live backend data. More
broadly, the work demonstrates a reproducible methodology for building domain-specific
LLM assistants on accessible hardware, and identifies retrieval grounding and stronger
evaluation as the primary directions for extending it toward production use.
"""